#! /bin/sh

sxhkd &
# set background
feh --bg-center /home/rationalplayer/stuff/wallpapers/green_texture_1_1280x800.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
