#! /bin/sh

sxhkd &
# prevent netbeans white screen
wmname compiz
# set background
if $(xdpyinfo | grep -q 1280x800); then
	feh --bg-center ~/images/wallpapers/thinkpad-x201/green_texture_1_1280x800.jpg
else
	feh --bg-center ~/images/wallpapers/workstation/darkpurple_landscape_1_2560x1080.jpg	
fi

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
